sudo: required
language: generic
services: docker
tex-config:
- tex-scheme=small
- push-type=branch
- build-pattern=posthoc.tex
- packages=lipsum, blindtext
env:
  global:
  - IS_TRAVIS=true
  - secure: uBdoqNbctNluBWY/g8HLR728iTgbD1rN9Di2LK8Stdfr3e6BMKXMl45g0f7B86h4ttQY3VRmKUMZzXkBInvOholn01n1LZso8Snm5Il/WRbuM5z/3M0fJOrzyUkvxthjF0tclbEMLTSPFGfZboL9wNSqhxk8Kmvbe0eYlZkq5XouZdfrRdyec4V5I18IV44wjnEV9ZVKn7rs8h04rP3yBLm8tbGqLgGJPtdXSR9wSGNbBjSr4SSXg7S3jgY55k0M5MW5FMLisyHYcBjauUlYQuF8F/sPPnnqxVRD6Iqf6HYLJuz03DNmgN0lTKujYLvVTSp6h+0c81krqfHeuohn0IioDCL/744S2Bz8zROG3KZr5whbwdOVrgoF1DUtC3bTVy6xE6AQWP7tTSSI7KWBaHwVy63cewS+szmoCgWiZRHf8lbDA72SLN9yQS2mPofkAQqfsAMT6RSeGy5atZX33vmv9NvFpG9m6Dh8cPSE/qY65p5rTejp5vbfi+QXT+H4wPEgtGJH0htpSskpioiOcZak6OadtOIoTfyu2tu01p0Zf01W+RN7/rqhYhTnJgJRNgg9vlKr7STixP98mMP8XMeUb/Wbc5JqFAm5ZMjt72M4j4l0n/aB0TgfWaJL83F7y0XNLjnBKSrJDcHw2NImNEZ2h0kSMsfb5gWM3Kbrg38=
script:
- chmod +x .travis/travis-texbuild.sh
- ".travis/travis-texbuild.sh"
