sudo: required
language: generic
services: docker
tex-config:
- tex-scheme=full
- push-type=branch
- build-pattern=posthoc.tex
- packages=lipsum, blindtext, framed
env:
  global:
  - IS_TRAVIS=true
  - secure: JW4cj4+adE8vZMvzuT27SmFW777IlqcV3I+WUMj4L4ZGvJ1/F4scQLujcs8/L//vQ9gpV1OxGiMPPa5qW2az/fOuY0zY3BxqkPzzAMRZeyLQhGevAOmdD2DWwr+wCa/her9Ry+VvD6uHvPRVSsDUp6mm+F1FdEPAYrbifhep43n3qVKY7tgzxMol5pdU6+CptMmpZ7NzrbR+Z4AxRFmx8JmPKKL3agUGuqsvdJ+T73V+DJS/uhhOH6+3YXULeJXfeFCVFTbIlnX5rwSEJJYtW68+Z8xnlpD8rLrSFqpL3NFOS307LKs/URjglNnNGwiLyrRaJQUXLcIEzjmwiMe4/FroxpHMmcqZv89t3Ps//O2gTDPQCC3WlIeCPpY/QZ424wzw1hwUSz9nLEdVR1sN0sjLY/FB4qHEiSEviZf5gb7EJfNTd4DfxkxUbxRpuxfmMOTmSR0dbDwFKODmTLMYJP04sjlBjwZPx474fv7jG7TGLcsHYqdZOpMGIhUHJNkQG562LpbHiIFZ2wG61y63F5JyMIQCx7bqiLFxpCc3F1MFMadMY/VACZqhpYcBlhtwuVOtQT5PGe3fTM1M8MD81U6ZXQ2vks+xz8G0xlZTRRsN5lAJPxwLj8HmPm941ao3d35k8ZGIY4bhXt3ypyXpIgAgw1vpbunltZGOavNAzL0=
script:
- chmod +x .travis/travis-texbuild.sh
- ".travis/travis-texbuild.sh"
